services:
  - type: web
    name: shekinah-api
    env: node
    autoDeploy: true
    plan: free
    buildCommand: cd server && npm ci && npm run build
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1

